// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/56295f5058cac7ae458540423c50ac2dcf9fc711/split/split.d.ts
declare module "split" {

    interface SplitOptions {
        maxLength: number
    }

    function split(matcher?:any, mapper?:any, options?: SplitOptions):any;

    export = split;
}
