// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/56295f5058cac7ae458540423c50ac2dcf9fc711/utils-merge/utils-merge.d.ts
declare module "utils-merge" {
	function merge<TA, TB, TResult>(a: TA, b: TB): TResult;

	export default merge;
}
